server:
  port: 8080

spring:
    datasource:
        url: "jdbc:postgresql://eof.h.filess.io:5432/MedsysDB_friendlywe"
        username: "MedsysDB_friendlywe"
        password: "e77b3518b9a9a6b816ba0a840aa3f9f6f2be93fd"
        driver-class-name: org.postgresql.Driver

